FROM node:22-alpine AS base
RUN apk update
RUN apk add --no-cache libc6-compat
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
# Set working directory
WORKDIR /app

FROM base AS builder
RUN pnpm add -g turbo@^2
COPY ../api .
RUN turbo prune --scope=helm-api --docker

# Add lockfile and package.json's of isolated subworkspace
FROM base AS installer
# First install dependencies (as they change less often)
COPY .gitignore .gitignore
COPY --from=builder /app/out/json/ .
RUN pnpm install

# Build the project and its dependencies
COPY --from=builder /app/out/full/ .
COPY turbo.json turbo.json

FROM base AS runner

COPY --from=installer ./app ./

ARG DB_HOST
ENV DB_HOST=$DB_HOST
ARG DB_USERNAME
ENV DB_USERNAME=$DB_USERNAME
ARG DB_PASSWORD
ENV DB_PASSWORD=$DB_PASSWORD
ARG DB_NAME
ENV DB_NAME=$DB_NAME

RUN npx pnpm install --global pnpm

CMD ["npx", "turbo", "migrate:up"]
